// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: Dashboard_UI

#ifndef _DASHBOARD_UI_UI_H
#define _DASHBOARD_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


// SCREEN: ui_Screen_Main
void ui_Screen_Main_screen_init(void);
extern lv_obj_t * ui_Screen_Main;
extern lv_obj_t * ui_RightArrow;
extern lv_obj_t * ui_LeftArrow;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_SpeedLabel;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_ExampleWhite;
extern lv_obj_t * ui_ExampleYellow;
extern lv_obj_t * ui_ExampleRed;
extern lv_obj_t * ui_PowerLevel;
extern lv_obj_t * ui_BatLevel;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image5;
// CUSTOM VARIABLES

// SCREEN: ui_Screen_Loading
void ui_Screen_Loading_screen_init(void);
extern lv_obj_t * ui_Screen_Loading;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_NotConnected;
// CUSTOM VARIABLES

// SCREEN: ui_Screen_Dark
void ui_Screen_Dark_screen_init(void);
extern lv_obj_t * ui_Screen_Dark;
// CUSTOM VARIABLES

// SCREEN: ui_Battery_Screen
void ui_Battery_Screen_screen_init(void);
extern lv_obj_t * ui_Battery_Screen;
extern lv_obj_t * ui_batt_info;
extern lv_obj_t * ui_cell_average;
extern lv_obj_t * ui_cell_max;
extern lv_obj_t * ui_cell_min;
extern lv_obj_t * ui_Pack_1;
extern lv_obj_t * ui_Pack_;
extern lv_obj_t * ui_Pack_3;
extern lv_obj_t * ui_Pack_5;
extern lv_obj_t * ui_Pack_6;
extern lv_obj_t * ui_Pack_7;
extern lv_obj_t * ui_Pack_8;
extern lv_obj_t * ui_Pack_9;
extern lv_obj_t * ui_Pack_10;
extern lv_obj_t * ui_Pack_11;
extern lv_obj_t * ui_Pack_12;
extern lv_obj_t * ui_Pack_13;
extern lv_obj_t * ui_Pack_14;
extern lv_obj_t * ui_Pack_15;
extern lv_obj_t * ui_Pack_16;
extern lv_obj_t * ui_Pack_17;
extern lv_obj_t * ui_Pack_18;
extern lv_obj_t * ui_Pack_25;
extern lv_obj_t * ui_Pack_19;
extern lv_obj_t * ui_Pack_20;
extern lv_obj_t * ui_Pack_21;
extern lv_obj_t * ui_Pack_22;
extern lv_obj_t * ui_Pack_23;
extern lv_obj_t * ui_Pack_24;
// CUSTOM VARIABLES
extern lv_obj_t * uic_cell_avg;
extern lv_obj_t * uic_cell_max;
extern lv_obj_t * uic_cell_min;
extern lv_obj_t * uic_pack_1;
extern lv_obj_t * uic_pack_7;
extern lv_obj_t * uic_pack_13;
extern lv_obj_t * uic_pack_2;
extern lv_obj_t * uic_pack_3;
extern lv_obj_t * uic_pack_4;
extern lv_obj_t * uic_pack_5;
extern lv_obj_t * uic_pack_6;
extern lv_obj_t * uic_pack_8;
extern lv_obj_t * uic_pack_9;
extern lv_obj_t * uic_pack_10;
extern lv_obj_t * uic_pack_11;
extern lv_obj_t * uic_pack_12;
extern lv_obj_t * uic_pack_14;
extern lv_obj_t * uic_pack_15;
extern lv_obj_t * uic_pack_16;
extern lv_obj_t * uic_pack_17;
extern lv_obj_t * uic_pack_18;
extern lv_obj_t * uic_pack_19;
extern lv_obj_t * uic_pack_20;
extern lv_obj_t * uic_pack_21;
extern lv_obj_t * uic_pack_22;
extern lv_obj_t * uic_pack_23;
extern lv_obj_t * uic_pack_24;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1346116439);    // assets/left-turn-signal.png
LV_IMG_DECLARE(ui_img_bolt_20dp_fill1_wght400_grad0_opsz20_png);    // assets/bolt_20dp_FILL1_wght400_GRAD0_opsz20.png
LV_IMG_DECLARE(
    ui_img_battery_full_20dp_fill1_wght400_grad0_opsz20_png);    // assets/battery_full_20dp_FILL1_wght400_GRAD0_opsz20.png
LV_IMG_DECLARE(ui_img_rusolar_resized_png);    // assets/RUSolar Resized.png
LV_IMG_DECLARE(ui_img_official_logo_square_1_png);    // assets/Official_Logo_Square_1.png

// FONTS
LV_FONT_DECLARE(ui_font_BarlowBold120);
LV_FONT_DECLARE(ui_font_BarlowBold32);
LV_FONT_DECLARE(ui_font_BarlowMedium20);
LV_FONT_DECLARE(ui_font_mono_font);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
