// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: Dashboard_UI

#include "../ui.h"

void ui_Battery_Screen_screen_init(void)
{
    ui_Battery_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Battery_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batt_info = lv_obj_create(ui_Battery_Screen);
    lv_obj_set_width(ui_batt_info, 450);
    lv_obj_set_height(ui_batt_info, 50);
    lv_obj_set_x(ui_batt_info, 0);
    lv_obj_set_y(ui_batt_info, -105);
    lv_obj_set_align(ui_batt_info, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_batt_info, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cell_average = lv_label_create(ui_Battery_Screen);
    lv_obj_set_width(ui_cell_average, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cell_average, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cell_average, 0);
    lv_obj_set_y(ui_cell_average, -105);
    lv_obj_set_align(ui_cell_average, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cell_average, "AVG XX.XX V");
    lv_obj_set_style_text_font(ui_cell_average, &ui_font_mono_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cell_max = lv_label_create(ui_Battery_Screen);
    lv_obj_set_width(ui_cell_max, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cell_max, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cell_max, -125);
    lv_obj_set_y(ui_cell_max, -105);
    lv_obj_set_align(ui_cell_max, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cell_max, "MAX XX.XX V");
    lv_obj_set_style_text_font(ui_cell_max, &ui_font_mono_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cell_min = lv_label_create(ui_Battery_Screen);
    lv_obj_set_width(ui_cell_min, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cell_min, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cell_min, 125);
    lv_obj_set_y(ui_cell_min, -105);
    lv_obj_set_align(ui_cell_min, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cell_min, "MIN XX.XX V");
    lv_obj_set_style_text_font(ui_cell_min, &ui_font_mono_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pack_1 = lv_label_create(ui_Battery_Screen);
    lv_obj_set_width(ui_Pack_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pack_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pack_1, -150);
    lv_obj_set_y(ui_Pack_1, -60);
    lv_obj_set_align(ui_Pack_1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pack_1, "P01 XX.XX V");
    lv_obj_set_style_text_font(ui_Pack_1, &ui_font_mono_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pack_ = lv_label_create(ui_Battery_Screen);
    lv_obj_set_width(ui_Pack_, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pack_, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pack_, -50);
    lv_obj_set_y(ui_Pack_, -60);
    lv_obj_set_align(ui_Pack_, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pack_, "P07 XX.XX V");
    lv_obj_set_style_text_font(ui_Pack_, &ui_font_mono_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pack_3 = lv_label_create(ui_Battery_Screen);
    lv_obj_set_width(ui_Pack_3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pack_3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pack_3, 50);
    lv_obj_set_y(ui_Pack_3, -60);
    lv_obj_set_align(ui_Pack_3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pack_3, "P13 XX.XX V");
    lv_obj_set_style_text_font(ui_Pack_3, &ui_font_mono_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pack_5 = lv_label_create(ui_Battery_Screen);
    lv_obj_set_width(ui_Pack_5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pack_5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pack_5, -150);
    lv_obj_set_y(ui_Pack_5, -35);
    lv_obj_set_align(ui_Pack_5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pack_5, "P02 XX.XX V");
    lv_obj_set_style_text_font(ui_Pack_5, &ui_font_mono_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pack_6 = lv_label_create(ui_Battery_Screen);
    lv_obj_set_width(ui_Pack_6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pack_6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pack_6, -150);
    lv_obj_set_y(ui_Pack_6, -10);
    lv_obj_set_align(ui_Pack_6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pack_6, "P03 XX.XX V");
    lv_obj_set_style_text_font(ui_Pack_6, &ui_font_mono_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pack_7 = lv_label_create(ui_Battery_Screen);
    lv_obj_set_width(ui_Pack_7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pack_7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pack_7, -150);
    lv_obj_set_y(ui_Pack_7, 15);
    lv_obj_set_align(ui_Pack_7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pack_7, "P04 XX.XX V");
    lv_obj_set_style_text_font(ui_Pack_7, &ui_font_mono_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pack_8 = lv_label_create(ui_Battery_Screen);
    lv_obj_set_width(ui_Pack_8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pack_8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pack_8, -150);
    lv_obj_set_y(ui_Pack_8, 40);
    lv_obj_set_align(ui_Pack_8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pack_8, "P05 XX.XX V");
    lv_obj_set_style_text_font(ui_Pack_8, &ui_font_mono_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pack_9 = lv_label_create(ui_Battery_Screen);
    lv_obj_set_width(ui_Pack_9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pack_9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pack_9, -150);
    lv_obj_set_y(ui_Pack_9, 65);
    lv_obj_set_align(ui_Pack_9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pack_9, "P06 XX.XX V");
    lv_obj_set_style_text_font(ui_Pack_9, &ui_font_mono_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pack_10 = lv_label_create(ui_Battery_Screen);
    lv_obj_set_width(ui_Pack_10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pack_10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pack_10, -50);
    lv_obj_set_y(ui_Pack_10, -35);
    lv_obj_set_align(ui_Pack_10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pack_10, "P08 XX.XX V");
    lv_obj_set_style_text_font(ui_Pack_10, &ui_font_mono_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pack_11 = lv_label_create(ui_Battery_Screen);
    lv_obj_set_width(ui_Pack_11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pack_11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pack_11, -50);
    lv_obj_set_y(ui_Pack_11, -10);
    lv_obj_set_align(ui_Pack_11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pack_11, "P09 XX.XX V");
    lv_obj_set_style_text_font(ui_Pack_11, &ui_font_mono_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pack_12 = lv_label_create(ui_Battery_Screen);
    lv_obj_set_width(ui_Pack_12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pack_12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pack_12, -50);
    lv_obj_set_y(ui_Pack_12, 15);
    lv_obj_set_align(ui_Pack_12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pack_12, "P10 XX.XX V");
    lv_obj_set_style_text_font(ui_Pack_12, &ui_font_mono_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pack_13 = lv_label_create(ui_Battery_Screen);
    lv_obj_set_width(ui_Pack_13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pack_13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pack_13, -50);
    lv_obj_set_y(ui_Pack_13, 40);
    lv_obj_set_align(ui_Pack_13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pack_13, "P11 XX.XX V");
    lv_obj_set_style_text_font(ui_Pack_13, &ui_font_mono_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pack_14 = lv_label_create(ui_Battery_Screen);
    lv_obj_set_width(ui_Pack_14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pack_14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pack_14, -50);
    lv_obj_set_y(ui_Pack_14, 65);
    lv_obj_set_align(ui_Pack_14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pack_14, "P12 XX.XX V");
    lv_obj_set_style_text_font(ui_Pack_14, &ui_font_mono_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pack_15 = lv_label_create(ui_Battery_Screen);
    lv_obj_set_width(ui_Pack_15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pack_15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pack_15, 50);
    lv_obj_set_y(ui_Pack_15, -35);
    lv_obj_set_align(ui_Pack_15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pack_15, "P14 XX.XX V");
    lv_obj_set_style_text_font(ui_Pack_15, &ui_font_mono_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pack_16 = lv_label_create(ui_Battery_Screen);
    lv_obj_set_width(ui_Pack_16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pack_16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pack_16, 50);
    lv_obj_set_y(ui_Pack_16, -10);
    lv_obj_set_align(ui_Pack_16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pack_16, "P15 XX.XX V");
    lv_obj_set_style_text_font(ui_Pack_16, &ui_font_mono_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pack_17 = lv_label_create(ui_Battery_Screen);
    lv_obj_set_width(ui_Pack_17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pack_17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pack_17, 50);
    lv_obj_set_y(ui_Pack_17, 15);
    lv_obj_set_align(ui_Pack_17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pack_17, "P16 XX.XX V");
    lv_obj_set_style_text_font(ui_Pack_17, &ui_font_mono_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pack_18 = lv_label_create(ui_Battery_Screen);
    lv_obj_set_width(ui_Pack_18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pack_18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pack_18, 50);
    lv_obj_set_y(ui_Pack_18, 40);
    lv_obj_set_align(ui_Pack_18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pack_18, "P17 XX.XX V");
    lv_obj_set_style_text_font(ui_Pack_18, &ui_font_mono_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pack_25 = lv_label_create(ui_Battery_Screen);
    lv_obj_set_width(ui_Pack_25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pack_25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pack_25, 50);
    lv_obj_set_y(ui_Pack_25, 65);
    lv_obj_set_align(ui_Pack_25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pack_25, "P18 XX.XX V");
    lv_obj_set_style_text_font(ui_Pack_25, &ui_font_mono_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pack_19 = lv_label_create(ui_Battery_Screen);
    lv_obj_set_width(ui_Pack_19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pack_19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pack_19, 150);
    lv_obj_set_y(ui_Pack_19, -60);
    lv_obj_set_align(ui_Pack_19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pack_19, "P19 XX.XX V");
    lv_obj_set_style_text_font(ui_Pack_19, &ui_font_mono_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pack_20 = lv_label_create(ui_Battery_Screen);
    lv_obj_set_width(ui_Pack_20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pack_20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pack_20, 150);
    lv_obj_set_y(ui_Pack_20, -35);
    lv_obj_set_align(ui_Pack_20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pack_20, "P20 XX.XX V");
    lv_obj_set_style_text_font(ui_Pack_20, &ui_font_mono_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pack_21 = lv_label_create(ui_Battery_Screen);
    lv_obj_set_width(ui_Pack_21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pack_21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pack_21, 150);
    lv_obj_set_y(ui_Pack_21, -10);
    lv_obj_set_align(ui_Pack_21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pack_21, "P21 XX.XX V");
    lv_obj_set_style_text_font(ui_Pack_21, &ui_font_mono_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pack_22 = lv_label_create(ui_Battery_Screen);
    lv_obj_set_width(ui_Pack_22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pack_22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pack_22, 150);
    lv_obj_set_y(ui_Pack_22, 15);
    lv_obj_set_align(ui_Pack_22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pack_22, "P22 XX.XX V");
    lv_obj_set_style_text_font(ui_Pack_22, &ui_font_mono_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pack_23 = lv_label_create(ui_Battery_Screen);
    lv_obj_set_width(ui_Pack_23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pack_23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pack_23, 150);
    lv_obj_set_y(ui_Pack_23, 40);
    lv_obj_set_align(ui_Pack_23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pack_23, "P23 XX.XX V");
    lv_obj_set_style_text_font(ui_Pack_23, &ui_font_mono_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pack_24 = lv_label_create(ui_Battery_Screen);
    lv_obj_set_width(ui_Pack_24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pack_24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pack_24, 150);
    lv_obj_set_y(ui_Pack_24, 65);
    lv_obj_set_align(ui_Pack_24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Pack_24, "P24 XX.XX V");
    lv_obj_set_style_text_font(ui_Pack_24, &ui_font_mono_font, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_cell_avg = ui_cell_average;
    uic_cell_max = ui_cell_max;
    uic_cell_min = ui_cell_min;
    uic_pack_1 = ui_Pack_1;
    uic_pack_7 = ui_Pack_;
    uic_pack_13 = ui_Pack_3;
    uic_pack_2 = ui_Pack_5;
    uic_pack_3 = ui_Pack_6;
    uic_pack_4 = ui_Pack_7;
    uic_pack_5 = ui_Pack_8;
    uic_pack_6 = ui_Pack_9;
    uic_pack_8 = ui_Pack_10;
    uic_pack_9 = ui_Pack_11;
    uic_pack_10 = ui_Pack_12;
    uic_pack_11 = ui_Pack_13;
    uic_pack_12 = ui_Pack_14;
    uic_pack_14 = ui_Pack_15;
    uic_pack_15 = ui_Pack_16;
    uic_pack_16 = ui_Pack_17;
    uic_pack_17 = ui_Pack_18;
    uic_pack_18 = ui_Pack_25;
    uic_pack_19 = ui_Pack_19;
    uic_pack_20 = ui_Pack_20;
    uic_pack_21 = ui_Pack_21;
    uic_pack_22 = ui_Pack_22;
    uic_pack_23 = ui_Pack_23;
    uic_pack_24 = ui_Pack_24;

}
